#ifndef GUARD_PLAYER_ENUMS_H
#define GUARD_PLAYER_ENUMS_H

enum Transformations {
    TRANSFORMATION_BANJO,
    TRANSFORMATION_MOUSE,
    TRANSFORMATION_CANDLE,
    TRANSFORMATION_TANK,
    TRANSFORMATION_OCTOPUS,
};

enum Moves {
    MOVE_0,
    MOVE_PACK_WACK,
    MOVE_FORWARD_ROLL,
    MOVE_AIR_ATTACK,
    MOVE_DRILL_BILL,
    MOVE_WONDERWING,
    MOVE_EGG_BLUE,
    MOVE_EGG_ELECTRIC,
    MOVE_EGG_ICE,
    MOVE_EGG_FIRE,
    MOVE_CANDLE_ATTACK,
    MOVE_11,
    MOVE_12,
    MOVE_13,
    MOVE_14,
    MOVE_TALON_TROT,
    MOVE_16,
    MOVE_17,
    MOVE_CLIMB,
    MOVE_FEATHERY_FLAP,
    MOVE_FLAP_FLIP,
    MOVE_DIVE,
    MOVE_SHOCK_JUMP,

    MOVE_COUNT
};

enum PlayerStates {
    PLAYER_STATE_IDLE,
    PLAYER_STATE_JUMP,
    PLAYER_STATE_CROUCH,
    PLAYER_STATE_CLIMB,
    PLAYER_STATE_WALK,
    PLAYER_STATE_SWIM,
    PLAYER_STATE_DIVE,
    PLAYER_STATE_FORWARD_ROLL_LEDGE_FALL,
    PLAYER_STATE_PACK_WACK_START,
    PLAYER_STATE_SHOOTER_START,
    PLAYER_STATE_KAZOOIE_WALK,
    PLAYER_STATE_KAZOOIE_JUMP,
    PLAYER_STATE_KAZOOIE_IDLE,
    PLAYER_STATE_FORWARD_ROLL,
    PLAYER_STATE_FEATHERY_FLAP,
    PLAYER_STATE_FLAP_FLIP,
    PLAYER_STATE_BILL_DRILL_START,
    PLAYER_STATE_AIR_ATTACK,
    PLAYER_STATE_JUMP_FALL,
    PLAYER_STATE_LEDGE_FALL,
    PLAYER_STATE_KAZOOIE_FALL,
    PLAYER_STATE_FLAP_FLIP_FALL,
    PLAYER_STATE_KAZOOIE_LEDGE_FALL,
    PLAYER_STATE_BILL_DRILL_END,
    PLAYER_STATE_BILL_DRILL_FALL,
    PLAYER_STATE_BILL_DRILL_HIT,
    PLAYER_STATE_26,
    PLAYER_STATE_SWIM_IDLE,
    PLAYER_STATE_PACK_WACK_HIT,
    PLAYER_STATE_HURT,
    PLAYER_STATE_KAZOOIE_HURT,
    PLAYER_STATE_DIE,
    PLAYER_STATE_DIALOGUE,
    PLAYER_STATE_SHOOTER_JUMP,
    PLAYER_STATE_SHOOTER_FALL,
    PLAYER_STATE_35,
    PLAYER_STATE_SHOCK_JUMP,
    PLAYER_STATE_SHOCK_JUMP_FALL,
    PLAYER_STATE_SHOCK_JUMP_START,
    PLAYER_STATE_WONDERWING_IDLE,
    PLAYER_STATE_WONDERWING_WALK,
    PLAYER_STATE_WONDERWING_JUMP,
    PLAYER_STATE_WONDERWING_FALL,
    PLAYER_STATE_WONDERWING_LEDGE_FALL,
    PLAYER_STATE_DIALOGUE_END,
    PLAYER_STATE_DIVE_SINK,
    PLAYER_STATE_DIVE_RISE,
    PLAYER_STATE_47,
    PLAYER_STATE_DIVE_SURFACE,
    PLAYER_STATE_MOUSE_WALK,
    PLAYER_STATE_MOUSE_IDLE,
    PLAYER_STATE_MOUSE_JUMP,
    PLAYER_STATE_MOUSE_JUMP_FALL,
    PLAYER_STATE_MOUSE_LEDGE_FALL,
    PLAYER_STATE_MOUSE_NIBBLE,
    PLAYER_STATE_MOUSE_DIE,
    PLAYER_STATE_MOUSE_HURT,
    PLAYER_STATE_CANDLE_DIE,
    PLAYER_STATE_CANDLE_ATTACK,
    PLAYER_STATE_CANDLE_HURT,
    PLAYER_STATE_CANDLE_WALK,
    PLAYER_STATE_CANDLE_IDLE,
    PLAYER_STATE_CANDLE_JUMP,
    PLAYER_STATE_CANDLE_JUMP_FALL,
    PLAYER_STATE_CANDLE_LEDGE_FALL,
    PLAYER_STATE_CANDLE_JUMP_ATTACK_START,
    PLAYER_STATE_CANDLE_JUMP_ATTACK_END,
    PLAYER_STATE_WONDERWING_START,
    PLAYER_STATE_WONDERWING_END,
    PLAYER_STATE_DIVE_HURT,
    PLAYER_STATE_SHOOTER_WALK,
    PLAYER_STATE_SHOOTER_IDLE,
    PLAYER_STATE_SHOOTER_HURT,
    PLAYER_STATE_SHOOTER_LEDGE_FALL,
    PLAYER_STATE_SHOOTER_END,
    PLAYER_STATE_TANK_RIDE,
    PLAYER_STATE_TANK_IDLE,
    PLAYER_STATE_TANK_DIE,
    PLAYER_STATE_TANK_LEDGE_FALL,
    PLAYER_STATE_TANK_HURT,
    PLAYER_STATE_OCTOPUS_IDLE,
    PLAYER_STATE_OCTOPUS_SWIM_IDLE,
    PLAYER_STATE_OCTOPUS_WALK,
    PLAYER_STATE_OCTOPUS_SWIM,
    PLAYER_STATE_OCTOPUS_DIVE_SINK,
    PLAYER_STATE_OCTOPUS_JUMP,
    PLAYER_STATE_OCTOPUS_JUMP_FALL,
    PLAYER_STATE_OCTOPUS_WATER_JUMP,
    PLAYER_STATE_OCTOPUS_WATER_JUMP_FALL,
    PLAYER_STATE_OCTOPUS_HURT,
    PLAYER_STATE_90,
    PLAYER_STATE_OCTOPUS_DIVE_HURT,
    PLAYER_STATE_OCTOPUS_DIE,
    PLAYER_STATE_OCTOPUS_LEDGE_FALL,
    PLAYER_STATE_OCTOPUS_DIVE,
    PLAYER_STATE_OCTOPUS_DIVE_RISE,
    PLAYER_STATE_OCTOPUS_DIVE_SURFACE,
    PLAYER_STATE_97,
    PLAYER_STATE_98,
    PLAYER_STATE_DIALOGUE_START,
    PLAYER_STATE_CANDLE_ATTACK_LEDGE_FALL,
    PLAYER_STATE_NONE,

    PLAYER_STATE_COUNT = 128
};

#define PLAYER_FLAGS_NONE                  (0 << 0)  // 0x0000
#define PLAYER_FLAGS_NOT_MOVING            (1 << 0)  // 0x0001
#define PLAYER_FLAGS_PACK_WACK             (1 << 1)  // 0x0002
#define PLAYER_FLAGS_SHOOTER_MODE          (1 << 2)  // 0x0004
#define PLAYER_FLAGS_IS_HURTING            (1 << 3)  // 0x0008
#define PLAYER_FLAGS_IN_AIR                (1 << 4)  // 0x0010
#define PLAYER_FLAGS_IS_FALLING_FROM_LEDGE (1 << 5)  // 0x0020
#define PLAYER_FLAGS_IS_CLIMBING           (1 << 6)  // 0x0040
#define PLAYER_FLAGS_DIVING_START          (1 << 7)  // 0x0080
#define PLAYER_FLAGS_IS_DIVING             (1 << 8)  // 0x0100
#define PLAYER_FLAGS_IS_SWIMMING           (1 << 9)  // 0x0200
#define PLAYER_FLAGS_BIT11                 (1 << 10) // 0x0400
#define PLAYER_FLAGS_IN_DIALOGUE           (1 << 11) // 0x0800
#define PLAYER_FLAGS_IS_DYING              (1 << 12) // 0x1000
#define PLAYER_FLAGS_IN_TRANSFORMATION     (1 << 13) // 0x2000
#define PLAYER_FLAGS_IN_WONDERWING_MODE    (1 << 14) // 0x4000
#define PLAYER_FLAGS_IN_KAZOOIE_MODE       (1 << 15) // 0x8000

#endif
