name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Make gbafix
        run: |
          make
        working-directory: tools/gbafix

      - name: Build
        run: |
          make

      - name: Calculate progress
        run: | 
          echo "PROGRESS=$(python3 score.py -p)" >> $GITHUB_ENV
      
      - name: Create progress badge
        uses: schneegans/dynamic-badges-action@v1.3.0
        with:
          auth: ${{ secrets.BKGR_PROGRESS_SECRET }}
          gistID: b35087f821408554ad6d43f1ca9b1399
          filename: bkgr-progress.json
          label: Progress
          message: ${{ env.PROGRESS }}%
          valColorRange: ${{ env.PROGRESS }}
          maxColorRange: 100
          minColorRange: 0